/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Black: typeof import('./components/Black.vue')['default']
    GlobalNavbar: typeof import('./components/GlobalNavbar.vue')['default']
    ImgNavbar: typeof import('./components/ImgNavbar.vue')['default']
    LayoutDefault: typeof import('./components/LayoutDefault.vue')['default']
    LayoutTabbar: typeof import('./components/LayoutTabbar.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['NutButton']
    NutCalendar: typeof import('nutui-uniapp/components/calendar/calendar.vue')['NutCalendar']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['NutCell']
    NutCellGroup: typeof import('nutui-uniapp/components/cellgroup/cellgroup.vue')['NutCellGroup']
    NutCheckbox: typeof import('nutui-uniapp/components/checkbox/checkbox.vue')['NutCheckbox']
    NutDatePicker: typeof import('nutui-uniapp/components/datepicker/datepicker.vue')['NutDatePicker']
    NutDialog: typeof import('nutui-uniapp/components/dialog/dialog.vue')['NutDialog']
    NutForm: typeof import('nutui-uniapp/components/form/form.vue')['NutForm']
    NutFormItem: typeof import('nutui-uniapp/components/formitem/formitem.vue')['NutFormItem']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['NutIcon']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['NutInput']
    NutList: typeof import('nutui-uniapp/components/list/list.vue')['NutList']
    NutNavbar: typeof import('nutui-uniapp/components/navbar/navbar.vue')['NutNavbar']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['NutPopup']
    NutSwipe: typeof import('nutui-uniapp/components/swipe/swipe.vue')['NutSwipe']
    NutToast: typeof import('nutui-uniapp/components/toast/toast.vue')['NutToast']
    PullList: typeof import('./components/pullList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./components/TabBar.vue')['default']
    UnlockRecordItem: typeof import('./components/UnlockRecordItem.vue')['default']
  }
}
